//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employeesEntities : DbContext
    {
        public employeesEntities()
            : base("name=employeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> departments { get; set; }
        public virtual DbSet<DepartmentEmployee> dept_emp { get; set; }
        public virtual DbSet<DepartmentManager> dept_manager { get; set; }
        public virtual DbSet<Employee> employees { get; set; }
        public virtual DbSet<Salary> salaries { get; set; }
        public virtual DbSet<Title> titles { get; set; }
        public virtual DbSet<CurrentDepartmentEmployeeView> current_dept_emp { get; set; }
        public virtual DbSet<DepartmentEmployeeLatestDateView> dept_emp_latest_date { get; set; }
    }
}
